/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class EmployeeHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeHomeScreen
     */
    String getUsername = "";
    public EmployeeHomeScreen(String username) {
        initComponents();
        this.getUsername = username;
        titleEmp.setText("Welcome "+username);
        AppraisalPanelEmp.setVisible(false);
        Resignation.setVisible(false);
        myDataPanel.setVisible(false);
        LeavePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        WelcomeDefaultLabelEmp = new javax.swing.JPanel();
        WelcomeImg = new javax.swing.JLabel();
        SideMenuPanel = new javax.swing.JPanel();
        titleEmp = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        MenuLabel = new javax.swing.JLabel();
        AppraisalButton = new javax.swing.JButton();
        LeaveRequestButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        ResignationButton = new javax.swing.JButton();
        SignOutEmpBtn = new javax.swing.JButton();
        SeperatorLine = new javax.swing.JSeparator();
        SeperatorLine2 = new javax.swing.JSeparator();
        AppraisalPanelEmp = new javax.swing.JPanel();
        titleEmp1 = new javax.swing.JLabel();
        WorkDeliveredLabel = new javax.swing.JLabel();
        SelfReviewLabel = new javax.swing.JLabel();
        LearningLabel = new javax.swing.JLabel();
        ImprovementLabel = new javax.swing.JLabel();
        WorkDeliverdPane = new javax.swing.JScrollPane();
        WorkDelivered = new javax.swing.JTextArea();
        LearningPane = new javax.swing.JScrollPane();
        Learning = new javax.swing.JTextArea();
        ImprovementPane = new javax.swing.JScrollPane();
        Improvement = new javax.swing.JTextArea();
        SelfReviewPane = new javax.swing.JScrollPane();
        SelfReview = new javax.swing.JTextArea();
        Submit = new javax.swing.JButton();
        rating = new javax.swing.JTextField();
        HRCommentPane = new javax.swing.JScrollPane();
        Comment = new javax.swing.JTextArea();
        HRCommentLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        Resignation = new javax.swing.JPanel();
        EmpSep = new javax.swing.JLabel();
        ReasonLabel = new javax.swing.JLabel();
        ReasonTxtPane = new javax.swing.JScrollPane();
        ReasonTxt = new javax.swing.JTextArea();
        AcceptBtn = new javax.swing.JButton();
        StatusTxt = new javax.swing.JTextField();
        HROfferPane = new javax.swing.JScrollPane();
        OffetTxt = new javax.swing.JTextArea();
        offerLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        ResignRequest = new javax.swing.JButton();
        RejectBtn = new javax.swing.JButton();
        myDataPanel = new javax.swing.JPanel();
        titleEmp2 = new javax.swing.JLabel();
        Details = new javax.swing.JTabbedPane();
        PersonalDetailTab = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        MobileLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        FatherNameLabel = new javax.swing.JLabel();
        MotherNameLabel = new javax.swing.JLabel();
        OccupationLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        MobileField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        FatherField = new javax.swing.JTextField();
        MotherField = new javax.swing.JTextField();
        OccupationField = new javax.swing.JTextField();
        AddressTab = new javax.swing.JPanel();
        LocalityLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        CountruLabel = new javax.swing.JLabel();
        PinCodeLabel = new javax.swing.JLabel();
        LocalityField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        pincodeField = new javax.swing.JTextField();
        EducationTab = new javax.swing.JPanel();
        HighSchoolLabel = new javax.swing.JLabel();
        HighSchoolCGPALabel = new javax.swing.JLabel();
        HighSchoolCollegeLabel = new javax.swing.JLabel();
        highschoolFieldCGPA = new javax.swing.JTextField();
        highschoolField = new javax.swing.JTextField();
        InterLabel = new javax.swing.JLabel();
        InterCGPALabel = new javax.swing.JLabel();
        InterCollegeLabel = new javax.swing.JLabel();
        InterField = new javax.swing.JTextField();
        interFieldCGPA = new javax.swing.JTextField();
        GraduationLabel = new javax.swing.JLabel();
        GraduationCGPALabel = new javax.swing.JLabel();
        GraduationCollegeLabel = new javax.swing.JLabel();
        graduationField = new javax.swing.JTextField();
        graduationFieldCGPA = new javax.swing.JTextField();
        ChangePasswordTab = new javax.swing.JPanel();
        OldPasswordLabel = new javax.swing.JLabel();
        NewPasswordLabel = new javax.swing.JLabel();
        CnfNewPassLabel = new javax.swing.JLabel();
        ChngPassBtn = new javax.swing.JButton();
        CnfNewPass = new javax.swing.JPasswordField();
        OldPass = new javax.swing.JPasswordField();
        NewPass = new javax.swing.JPasswordField();
        LeavePanel = new javax.swing.JPanel();
        titleEmp3 = new javax.swing.JLabel();
        LeaveDetail = new javax.swing.JPanel();
        LeaveStartDateLabel = new javax.swing.JLabel();
        LeaveDaysLabel = new javax.swing.JLabel();
        LeaveReasonLabel = new javax.swing.JLabel();
        LeaveTypeLabel = new javax.swing.JLabel();
        SubmitLeaveRequest = new javax.swing.JButton();
        LeaveStartDateTxt = new javax.swing.JTextField();
        LeaveDaysTxt = new javax.swing.JTextField();
        LeaveReasonTxtPane = new javax.swing.JScrollPane();
        LeaveReasonTxt = new javax.swing.JTextArea();
        LeaveTypeList = new javax.swing.JComboBox<>();
        StatusLeave = new javax.swing.JTextField();
        StatusLabelLeave = new javax.swing.JLabel();
        LeaveData = new javax.swing.JPanel();
        LeaveTabelListPane = new javax.swing.JScrollPane();
        LeaveTableList = new javax.swing.JTable();
        ViewLeave = new javax.swing.JButton();
        ApplyNewLeave1 = new javax.swing.JButton();
        LeaveIDTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeDefaultLabelEmp.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeDefaultLabelEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeImg.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\welcome.jpg")); // NOI18N
        WelcomeDefaultLabelEmp.add(WelcomeImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        MainPanel.add(WelcomeDefaultLabelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 860, 620));

        SideMenuPanel.setBackground(new java.awt.Color(102, 102, 255));

        titleEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleEmp.setForeground(new java.awt.Color(255, 255, 255));
        titleEmp.setText("Welcome User");

        Icon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-administrator-male-100.png")); // NOI18N

        MenuLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        MenuLabel.setText("Menu");

        AppraisalButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        AppraisalButton.setText("Appraisal");
        AppraisalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppraisalButtonActionPerformed(evt);
            }
        });

        LeaveRequestButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        LeaveRequestButton.setText("Leave Request");
        LeaveRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveRequestButtonActionPerformed(evt);
            }
        });

        ProfileButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        ProfileButton.setText("Profile");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        ResignationButton.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        ResignationButton.setText("Resign");
        ResignationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResignationButtonActionPerformed(evt);
            }
        });

        SignOutEmpBtn.setBackground(new java.awt.Color(255, 51, 51));
        SignOutEmpBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        SignOutEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignOutEmpBtn.setText("Sign out");
        SignOutEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutEmpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideMenuPanelLayout = new javax.swing.GroupLayout(SideMenuPanel);
        SideMenuPanel.setLayout(SideMenuPanelLayout);
        SideMenuPanelLayout.setHorizontalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuPanelLayout.createSequentialGroup()
                .addGroup(SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideMenuPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Icon))
                    .addGroup(SideMenuPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AppraisalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LeaveRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResignationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignOutEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 63, Short.MAX_VALUE))
            .addComponent(SeperatorLine)
            .addComponent(SeperatorLine2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuPanelLayout.createSequentialGroup()
                        .addComponent(titleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuPanelLayout.createSequentialGroup()
                        .addComponent(MenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        SideMenuPanelLayout.setVerticalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleEmp)
                .addGap(33, 33, 33)
                .addComponent(SeperatorLine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MenuLabel)
                .addGap(7, 7, 7)
                .addComponent(SeperatorLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(AppraisalButton)
                .addGap(18, 18, 18)
                .addComponent(LeaveRequestButton)
                .addGap(18, 18, 18)
                .addComponent(ProfileButton)
                .addGap(18, 18, 18)
                .addComponent(ResignationButton)
                .addGap(18, 18, 18)
                .addComponent(SignOutEmpBtn)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        MainPanel.add(SideMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 630));

        AppraisalPanelEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleEmp1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleEmp1.setText("Appraisal");
        AppraisalPanelEmp.add(titleEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, -1));

        WorkDeliveredLabel.setText("Work Delivered in Last Cycle");
        AppraisalPanelEmp.add(WorkDeliveredLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        SelfReviewLabel.setText("Self Review");
        AppraisalPanelEmp.add(SelfReviewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        LearningLabel.setText("Learning from Last Cycle");
        AppraisalPanelEmp.add(LearningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        ImprovementLabel.setText("Possible Improvement  in Next Cycle");
        AppraisalPanelEmp.add(ImprovementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        WorkDelivered.setColumns(20);
        WorkDelivered.setRows(5);
        WorkDeliverdPane.setViewportView(WorkDelivered);

        AppraisalPanelEmp.add(WorkDeliverdPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 320, -1));

        Learning.setColumns(20);
        Learning.setRows(5);
        LearningPane.setViewportView(Learning);

        AppraisalPanelEmp.add(LearningPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 320, -1));

        Improvement.setColumns(20);
        Improvement.setRows(5);
        ImprovementPane.setViewportView(Improvement);

        AppraisalPanelEmp.add(ImprovementPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 300, -1));

        SelfReview.setColumns(20);
        SelfReview.setRows(5);
        SelfReviewPane.setViewportView(SelfReview);

        AppraisalPanelEmp.add(SelfReviewPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 300, -1));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        AppraisalPanelEmp.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 150, 50));
        AppraisalPanelEmp.add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, -1));

        Comment.setColumns(20);
        Comment.setRows(5);
        HRCommentPane.setViewportView(Comment);

        AppraisalPanelEmp.add(HRCommentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 320, -1));

        HRCommentLabel.setText("HR Comment");
        AppraisalPanelEmp.add(HRCommentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        RatingLabel.setText("Rating");
        AppraisalPanelEmp.add(RatingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        MainPanel.add(AppraisalPanelEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 860, 630));

        Resignation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpSep.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EmpSep.setText("Resignation");
        Resignation.add(EmpSep, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 150, -1));

        ReasonLabel.setText("Reason");
        Resignation.add(ReasonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        ReasonTxt.setColumns(20);
        ReasonTxt.setRows(5);
        ReasonTxtPane.setViewportView(ReasonTxt);

        Resignation.add(ReasonTxtPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 320, -1));

        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });
        Resignation.add(AcceptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 150, 50));

        StatusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusTxtActionPerformed(evt);
            }
        });
        Resignation.add(StatusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 320, 30));

        OffetTxt.setColumns(20);
        OffetTxt.setRows(5);
        HROfferPane.setViewportView(OffetTxt);

        Resignation.add(HROfferPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 320, -1));

        offerLabel.setText("HR Offer");
        Resignation.add(offerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 60, 20));

        StatusLabel.setText("Status");
        Resignation.add(StatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        ResignRequest.setText("Resign Request");
        ResignRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResignRequestActionPerformed(evt);
            }
        });
        Resignation.add(ResignRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 150, 50));

        RejectBtn.setText("Reject");
        RejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectBtnActionPerformed(evt);
            }
        });
        Resignation.add(RejectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 150, 50));

        MainPanel.add(Resignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 860, 630));

        myDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleEmp2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleEmp2.setText("myProfile");
        myDataPanel.add(titleEmp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, -1));

        Details.setBackground(new java.awt.Color(51, 51, 255));
        Details.setForeground(new java.awt.Color(255, 255, 255));
        Details.setToolTipText("");

        PersonalDetailTab.setBackground(new java.awt.Color(102, 102, 255));

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name");

        DOBLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(255, 255, 255));
        DOBLabel.setText("Date of Birth");

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgeLabel.setText("Age");

        MobileLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MobileLabel.setForeground(new java.awt.Color(255, 255, 255));
        MobileLabel.setText("Mobile");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email");

        FatherNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FatherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FatherNameLabel.setText("Father's Name");

        MotherNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MotherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        MotherNameLabel.setText("Mother's Name");

        OccupationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OccupationLabel.setForeground(new java.awt.Color(255, 255, 255));
        OccupationLabel.setText("Father's Occupation");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonalDetailTabLayout = new javax.swing.GroupLayout(PersonalDetailTab);
        PersonalDetailTab.setLayout(PersonalDetailTabLayout);
        PersonalDetailTabLayout.setHorizontalGroup(
            PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalDetailTabLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MobileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MotherNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FatherNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OccupationField)
                    .addComponent(AgeField)
                    .addComponent(emailField)
                    .addComponent(MobileField)
                    .addComponent(FatherField)
                    .addGroup(PersonalDetailTabLayout.createSequentialGroup()
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MotherField)
                    .addComponent(dobField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(117, 117, 117))
        );
        PersonalDetailTabLayout.setVerticalGroup(
            PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalDetailTabLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBLabel)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileLabel)
                    .addComponent(MobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FatherNameLabel)
                    .addComponent(FatherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotherNameLabel)
                    .addComponent(MotherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalDetailTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OccupationLabel)
                    .addComponent(OccupationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        Details.addTab("Personal Detail", PersonalDetailTab);

        AddressTab.setBackground(new java.awt.Color(102, 102, 255));

        LocalityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LocalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        LocalityLabel.setText("Locality");

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(255, 255, 255));
        CityLabel.setText("City");

        StateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateLabel.setText("State");

        CountruLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CountruLabel.setForeground(new java.awt.Color(255, 255, 255));
        CountruLabel.setText("Country");

        PinCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PinCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        PinCodeLabel.setText("Pin Code");

        javax.swing.GroupLayout AddressTabLayout = new javax.swing.GroupLayout(AddressTab);
        AddressTab.setLayout(AddressTabLayout);
        AddressTabLayout.setHorizontalGroup(
            AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressTabLayout.createSequentialGroup()
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddressTabLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddressTabLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(CountruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LocalityField)
                    .addComponent(cityField)
                    .addComponent(stateField)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(PinCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        AddressTabLayout.setVerticalGroup(
            AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressTabLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalityLabel)
                    .addComponent(PinCodeLabel)
                    .addComponent(LocalityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateLabel)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountruLabel)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        Details.addTab("Address Detail", AddressTab);

        EducationTab.setBackground(new java.awt.Color(102, 102, 255));

        HighSchoolLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighSchoolLabel.setForeground(new java.awt.Color(255, 255, 255));
        HighSchoolLabel.setText("Highschool");

        HighSchoolCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighSchoolCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        HighSchoolCGPALabel.setText("Percentage/CGPA");

        HighSchoolCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighSchoolCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HighSchoolCollegeLabel.setText("School/College");

        InterLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterLabel.setForeground(new java.awt.Color(255, 255, 255));
        InterLabel.setText("Intemediate");

        InterCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        InterCGPALabel.setText("Percentage/CGPA");

        InterCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        InterCollegeLabel.setText("School/College");

        GraduationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationLabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationLabel.setText("Graduation");

        GraduationCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationCGPALabel.setText("Percentage/CGPA");

        GraduationCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationCollegeLabel.setText("School/College");

        javax.swing.GroupLayout EducationTabLayout = new javax.swing.GroupLayout(EducationTab);
        EducationTab.setLayout(EducationTabLayout);
        EducationTabLayout.setHorizontalGroup(
            EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HighSchoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GraduationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EducationTabLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GraduationCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GraduationCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(graduationField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                            .addComponent(graduationFieldCGPA))))
                                .addGroup(EducationTabLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(InterCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InterCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(InterField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                        .addComponent(interFieldCGPA)))))
                        .addGroup(EducationTabLayout.createSequentialGroup()
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HighSchoolCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HighSchoolCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(highschoolField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                .addComponent(highschoolFieldCGPA)))))
                .addGap(0, 0, 0))
        );
        EducationTabLayout.setVerticalGroup(
            EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(HighSchoolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highschoolFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HighSchoolCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(highschoolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HighSchoolCollegeLabel)))
                .addGap(30, 30, 30)
                .addComponent(InterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InterCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(InterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InterCollegeLabel)))
                .addGap(30, 30, 30)
                .addComponent(GraduationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graduationFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GraduationCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(graduationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GraduationCollegeLabel)))
                .addGap(0, 0, 0))
        );

        Details.addTab("Education Detail", EducationTab);

        ChangePasswordTab.setBackground(new java.awt.Color(102, 102, 255));
        ChangePasswordTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OldPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OldPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        OldPasswordLabel.setText("Old  Password");
        OldPasswordLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                OldPasswordLabelFocusGained(evt);
            }
        });
        ChangePasswordTab.add(OldPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 131, -1));

        NewPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        NewPasswordLabel.setText("New Password");
        ChangePasswordTab.add(NewPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 131, -1));

        CnfNewPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CnfNewPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        CnfNewPassLabel.setText("Confirm New Password");
        ChangePasswordTab.add(CnfNewPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        ChngPassBtn.setText("Change Password");
        ChngPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChngPassBtnActionPerformed(evt);
            }
        });
        ChangePasswordTab.add(ChngPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 460, 30));
        ChangePasswordTab.add(CnfNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 290, -1));
        ChangePasswordTab.add(OldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 290, -1));
        ChangePasswordTab.add(NewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 290, -1));

        Details.addTab("Change Password", ChangePasswordTab);

        myDataPanel.add(Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 660, 370));

        MainPanel.add(myDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 860, 630));

        LeavePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleEmp3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleEmp3.setText("Leave Request");
        LeavePanel.add(titleEmp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 170, -1));

        LeaveDetail.setBackground(new java.awt.Color(102, 102, 255));
        LeaveDetail.setForeground(new java.awt.Color(255, 255, 255));
        LeaveDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaveStartDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaveStartDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        LeaveStartDateLabel.setText("Leave Start Date");
        LeaveDetail.add(LeaveStartDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        LeaveDaysLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaveDaysLabel.setForeground(new java.awt.Color(255, 255, 255));
        LeaveDaysLabel.setText("Leave Days");
        LeaveDetail.add(LeaveDaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 20));

        LeaveReasonLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaveReasonLabel.setForeground(new java.awt.Color(255, 255, 255));
        LeaveReasonLabel.setText("Leave Reason");
        LeaveDetail.add(LeaveReasonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 20));

        LeaveTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaveTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        LeaveTypeLabel.setText("Leave Type");
        LeaveDetail.add(LeaveTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 20));

        SubmitLeaveRequest.setText("Submit");
        SubmitLeaveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLeaveRequestActionPerformed(evt);
            }
        });
        LeaveDetail.add(SubmitLeaveRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 130, 40));
        LeaveDetail.add(LeaveStartDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 270, -1));
        LeaveDetail.add(LeaveDaysTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 270, -1));

        LeaveReasonTxt.setColumns(20);
        LeaveReasonTxt.setRows(5);
        LeaveReasonTxtPane.setViewportView(LeaveReasonTxt);

        LeaveDetail.add(LeaveReasonTxtPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 270, -1));

        LeaveTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick Leave", "Annual Leave", "Transfer Leave", "Leave Without Pay" }));
        LeaveDetail.add(LeaveTypeList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 270, -1));

        StatusLeave.setText("jTextField1");
        LeaveDetail.add(StatusLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 270, -1));

        StatusLabelLeave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StatusLabelLeave.setForeground(new java.awt.Color(255, 255, 255));
        StatusLabelLeave.setText("Status");
        LeaveDetail.add(StatusLabelLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 20));

        LeavePanel.add(LeaveDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 710, 470));

        LeaveData.setBackground(new java.awt.Color(102, 102, 255));
        LeaveData.setForeground(new java.awt.Color(255, 255, 255));
        LeaveData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaveTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Leave ID", "Date", "Days", "Status"
            }
        ));
        LeaveTableList.setGridColor(new java.awt.Color(204, 255, 255));
        LeaveTabelListPane.setViewportView(LeaveTableList);

        LeaveData.add(LeaveTabelListPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 650, 260));

        ViewLeave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewLeave.setForeground(new java.awt.Color(51, 51, 255));
        ViewLeave.setText("View Leave");
        ViewLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLeaveActionPerformed(evt);
            }
        });
        LeaveData.add(ViewLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 120, 30));

        ApplyNewLeave1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ApplyNewLeave1.setForeground(new java.awt.Color(51, 51, 255));
        ApplyNewLeave1.setText("Apply New Leave");
        ApplyNewLeave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyNewLeave1ActionPerformed(evt);
            }
        });
        LeaveData.add(ApplyNewLeave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, 30));
        LeaveData.add(LeaveIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 240, 30));

        LeavePanel.add(LeaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 710, 470));

        MainPanel.add(LeavePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 860, 630));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeaveRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveRequestButtonActionPerformed
        // TODO add your handling code here:
        LeavePanel.setVisible(true);
        LeaveData.setVisible(true);
        LeaveDetail.setVisible(false);
        myDataPanel.setVisible(false);
        Resignation.setVisible(false);
        AppraisalPanelEmp.setVisible(false);
        WelcomeDefaultLabelEmp.setVisible(false);
        LeaveTableSetValue();
    }//GEN-LAST:event_LeaveRequestButtonActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String user = getUsername;
        String workTxt = WorkDelivered.getText();
        String learningTxt = Learning.getText();
        String improvementTxt = Improvement.getText();
        String selfTxt = SelfReview.getText();
        DBConnection dbcon = new DBConnection();
        try {
            if(dbcon.checkAppraisalPresence(user)){
                dbcon.insertAppraisal(user, workTxt, learningTxt, improvementTxt, selfTxt);
                JOptionPane.showMessageDialog(null, "Appraisal Submitted! Please wait for HR review.......");
            }
            else{
                JOptionPane.showMessageDialog(null, "Appraisal Already Submitted.....");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not able to submit Appraisal");
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void AppraisalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppraisalButtonActionPerformed
        LeavePanel.setVisible(false);
        Resignation.setVisible(false);
        AppraisalPanelEmp.setVisible(true);
        WelcomeDefaultLabelEmp.setVisible(false);
        myDataPanel.setVisible(false);
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "")) {
         PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM appraisal WHERE Username = ? ");
         pstmt.setString(1, getUsername);
         ResultSet rs = pstmt.executeQuery();
         String work="";
         String improvement="";
         String learning="";
         String self="";
         String comment="";
         int ratingDone = 0;
         while(rs.next()) {
            WorkDelivered.setEditable(false);
            Improvement.setEditable(false);
            Learning.setEditable(false);
            SelfReview.setEditable(false);
            work = rs.getString("Work");
            improvement = rs.getString("improvement");
            learning = rs.getString("Learning");
            self = rs.getString("SelfReview");
            comment = rs.getString("Comment");
            ratingDone = rs.getInt("Rating");
         }
         WorkDelivered.setText(work);
         Improvement.setText(improvement);
         Learning.setText(learning);
         SelfReview.setText(self);
         Comment.setText(comment);
         rating.setText(Integer.toString(ratingDone));
         Comment.setEditable(false);
         rating.setEditable(false);
        }  catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AppraisalButtonActionPerformed

    private void SignOutEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutEmpBtnActionPerformed
        dispose();
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
    }//GEN-LAST:event_SignOutEmpBtnActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        // TODO add your handling code here:
        DBConnection dbconn = new DBConnection();
        try {
            dbconn.acceptHROffer( getUsername);
            JOptionPane.showMessageDialog(null, "Thank you! You have Accepted the HR offer, Please Login Again to Continue");
            SignOutEmpBtn.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void ResignationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResignationButtonActionPerformed
        // TODO add your handling code here:
        LeavePanel.setVisible(false);
        myDataPanel.setVisible(false);
        Resignation.setVisible(true);
        AppraisalPanelEmp.setVisible(false);
        WelcomeDefaultLabelEmp.setVisible(false);
        ResignRequest.setVisible(true);
        AcceptBtn.setVisible(false);
        RejectBtn.setVisible(false);
        OffetTxt.setEditable(false);
        StatusTxt.setEditable(false);
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "")) {
         PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM resignation WHERE Username = ? ");
         pstmt.setString(1, getUsername);
         ResultSet rs = pstmt.executeQuery();
         String reasonFetched="";
         String statusFetched="NEW";
         String offerFetched="";
         while(rs.next()) {
            ReasonTxt.setEditable(false);
            reasonFetched = rs.getString("reason");
            statusFetched = rs.getString("status");
            if(statusFetched.equalsIgnoreCase("OFFERED")){
                ResignRequest.setVisible(false);
                AcceptBtn.setVisible(true);
                RejectBtn.setVisible(true);
                offerFetched = rs.getString("offer");
                String message = "Hi!" + getUsername + "\nHR offered you " + offerFetched + "\nWould you like to continue with this offer ?";
                OffetTxt.setText(message);
            } 
         }
         ReasonTxt.setText(reasonFetched);
         StatusTxt.setText(statusFetched);
        }  catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ResignationButtonActionPerformed

    private void StatusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusTxtActionPerformed

    private void RejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectBtnActionPerformed
        // TODO add your handling code here:
        DBConnection dbconn = new DBConnection();
        try {
            dbconn.acceptHROffer( getUsername);
            dbconn.rejectHROffer( getUsername);
            JOptionPane.showMessageDialog(null, "Thank you for being our employee.. We are sorry to see you go");
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RejectBtnActionPerformed

    private void ResignRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResignRequestActionPerformed
        // TODO add your handling code here:
        String user = getUsername;
        String reason = ReasonTxt.getText();
        DBConnection dbcon = new DBConnection();
        try {
            if(dbcon.insertResignation(user, reason)){
                JOptionPane.showMessageDialog(null, "Resignation Request Submitted! Please wait for HR action.......");
            }
            else{
                 JOptionPane.showMessageDialog(null, "Request Already Submitted.....");
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not able to submit Resignation");
        }
    }//GEN-LAST:event_ResignRequestActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        LeavePanel.setVisible(false);
        myDataPanel.setVisible(true);
        Resignation.setVisible(false);
        AppraisalPanelEmp.setVisible(false);
        WelcomeDefaultLabelEmp.setVisible(false);
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "")) {
         PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM personaldetail WHERE Username = ? ");
         pstmt.setString(1, getUsername);
         ResultSet rs = pstmt.executeQuery();
         NameField.setEditable(false);
         dobField.setEditable(false);
         AgeField.setEditable(false);
         MobileField.setEditable(false);
         emailField.setEditable(false);
         FatherField.setEditable(false);
         MotherField.setEditable(false);
         OccupationField.setEditable(false);
         LocalityField.setEditable(false);
         cityField.setEditable(false);
         stateField.setEditable(false);
         countryField.setEditable(false);
         pincodeField.setEditable(false);
         highschoolFieldCGPA.setEditable(false);
         highschoolField.setEditable(false);
         interFieldCGPA.setEditable(false);
         InterField.setEditable(false);
         graduationFieldCGPA.setEditable(false);
         graduationField.setEditable(false);

         while(rs.next()) {
            NameField.setText(rs.getString("Name"));
            dobField.setText(rs.getString("DOB"));
            AgeField.setText(Integer.toString(rs.getInt("Age")));
            MobileField.setText(rs.getString("Mobile"));
            emailField.setText(rs.getString("Email"));
            FatherField.setText(rs.getString("Fathername"));
            MotherField.setText(rs.getString("Mothername"));
            OccupationField.setText(rs.getString("Fatheroccupation"));
            LocalityField.setText(rs.getString("Locality"));
            cityField.setText(rs.getString("City"));
            stateField.setText(rs.getString("State"));
            countryField.setText(rs.getString("Country"));
            pincodeField.setText(rs.getString("Pincode"));
            highschoolFieldCGPA.setText(rs.getString("HighschoolCGPA"));
            highschoolField.setText(rs.getString("HighschoolCLG"));
            interFieldCGPA.setText(rs.getString("InterCGPA"));
            InterField.setText(rs.getString("InterCLG"));
            graduationFieldCGPA.setText(rs.getString("GraduationCGPA"));
            graduationField.setText(rs.getString("GraduationCLG"));
         }

        }  catch (SQLException ex) {
            Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void OldPasswordLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OldPasswordLabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_OldPasswordLabelFocusGained

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void ChngPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChngPassBtnActionPerformed
        // TODO add your handling code here:
        String OldPassword = new String(OldPass.getPassword());
        String NewPassword = new String(NewPass.getPassword());
        String CnfNewPassword = new String(CnfNewPass.getPassword());
        DBConnection dbcon = new DBConnection();
        try {
            String EcptdOldPassword = encryptPassword(OldPassword);
            String EcptdNewPassword = encryptPassword(NewPassword);
            
            if(NewPassword.equals(CnfNewPassword) && NewPassword.length() >= 8){
                String dbPassword = dbcon.getName("password",getUsername);
                if(dbPassword.equals(EcptdOldPassword)){
                    Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
                    PreparedStatement pstmt = conn.prepareStatement("Update personaldetail set Password = ? where Username = ?");
                    pstmt.setString(1, EcptdNewPassword);
                    pstmt.setString(2, getUsername);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Password Change Successfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please Enter correct Old Password");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "New Password and Confirm Password must be same and must be at least 8 Character");
            }
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ChngPassBtnActionPerformed

    private void SubmitLeaveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLeaveRequestActionPerformed
        // TODO add your handling code here:
            String startDate = LeaveStartDateTxt.getText();
            int days = Integer.parseInt(LeaveDaysTxt.getText());
            String type = String.valueOf(LeaveTypeList.getSelectedItem());
            String reason = LeaveReasonTxt.getText();
            Random rand = new Random();
            int id = rand.nextInt((99999999 - 10000000) + 10000000);
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "")) {
             PreparedStatement pstmt = conn.prepareStatement("INSERT INTO applyleave(ID,Username,Date,Days,Type,Reason,Status) VALUES(?,?,?,?,?,?,?)");
             pstmt.setInt(1, id);
             pstmt.setString(2, getUsername);
             pstmt.setString(3, startDate);
             pstmt.setInt(4, days);
             pstmt.setString(5, type);
             pstmt.setString(6, reason);
             if(type.equalsIgnoreCase("Sick Leave")){
                 pstmt.setString(7, "APPROVED");
             }
             else{
                 pstmt.setString(7, "New");
             }
             pstmt.executeUpdate();
             pstmt.close();
             conn.close();
             if(type.equalsIgnoreCase("Sick Leave")){
                 JOptionPane.showMessageDialog(null, "Leave Successfully Applied, and Auto Approved");
             }
             else{
                 JOptionPane.showMessageDialog(null, "Leave Successfully Applied.. Please Wair for Approval...");
             }
             
            }  
            catch (SQLException ex) {
                Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_SubmitLeaveRequestActionPerformed

    private void ViewLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLeaveActionPerformed

        String leaveId = LeaveIDTxt.getText();
        if(!leaveId.equalsIgnoreCase("")){
            LeaveData.setVisible(false);
            LeaveDetail.setVisible(true);
            StatusLabelLeave.setVisible(true);
            StatusLeave.setVisible(true);
            LeaveTypeList.setVisible(false);
            LeaveTypeLabel.setVisible(false);
            leaveDetailMethod(leaveId);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Leave ID");
        }
        
    }//GEN-LAST:event_ViewLeaveActionPerformed

    private void ApplyNewLeave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyNewLeave1ActionPerformed
        // TODO add your handling code here:
        SubmitLeaveRequest.setVisible(true);
        StatusLabelLeave.setVisible(false);
        StatusLeave.setVisible(false);
        LeaveTypeList.setVisible(true);
        LeaveTypeLabel.setVisible(true);
        LeaveData.setVisible(false);
        LeaveDetail.setVisible(true);
        LeaveStartDateTxt.setText("");
        LeaveDaysTxt.setText("");
        LeaveReasonTxt.setText("");
        StatusLeave.setText("");
        leaveDetailMethod("NEW");
    }//GEN-LAST:event_ApplyNewLeave1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EmployeeHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EmployeeHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EmployeeHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EmployeeHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EmployeeHomeScreen("").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JPanel AddressTab;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JButton ApplyNewLeave1;
    private javax.swing.JButton AppraisalButton;
    private javax.swing.JPanel AppraisalPanelEmp;
    private javax.swing.JPanel ChangePasswordTab;
    private javax.swing.JButton ChngPassBtn;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPasswordField CnfNewPass;
    private javax.swing.JLabel CnfNewPassLabel;
    private javax.swing.JTextArea Comment;
    private javax.swing.JLabel CountruLabel;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTabbedPane Details;
    private javax.swing.JPanel EducationTab;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmpSep;
    private javax.swing.JTextField FatherField;
    private javax.swing.JLabel FatherNameLabel;
    private javax.swing.JLabel GraduationCGPALabel;
    private javax.swing.JLabel GraduationCollegeLabel;
    private javax.swing.JLabel GraduationLabel;
    private javax.swing.JLabel HRCommentLabel;
    private javax.swing.JScrollPane HRCommentPane;
    private javax.swing.JScrollPane HROfferPane;
    private javax.swing.JLabel HighSchoolCGPALabel;
    private javax.swing.JLabel HighSchoolCollegeLabel;
    private javax.swing.JLabel HighSchoolLabel;
    private javax.swing.JLabel Icon;
    private javax.swing.JTextArea Improvement;
    private javax.swing.JLabel ImprovementLabel;
    private javax.swing.JScrollPane ImprovementPane;
    private javax.swing.JLabel InterCGPALabel;
    private javax.swing.JLabel InterCollegeLabel;
    private javax.swing.JTextField InterField;
    private javax.swing.JLabel InterLabel;
    private javax.swing.JTextArea Learning;
    private javax.swing.JLabel LearningLabel;
    private javax.swing.JScrollPane LearningPane;
    private javax.swing.JPanel LeaveData;
    private javax.swing.JLabel LeaveDaysLabel;
    private javax.swing.JTextField LeaveDaysTxt;
    private javax.swing.JPanel LeaveDetail;
    private javax.swing.JTextField LeaveIDTxt;
    private javax.swing.JPanel LeavePanel;
    private javax.swing.JLabel LeaveReasonLabel;
    private javax.swing.JTextArea LeaveReasonTxt;
    private javax.swing.JScrollPane LeaveReasonTxtPane;
    private javax.swing.JButton LeaveRequestButton;
    private javax.swing.JLabel LeaveStartDateLabel;
    private javax.swing.JTextField LeaveStartDateTxt;
    private javax.swing.JScrollPane LeaveTabelListPane;
    private javax.swing.JTable LeaveTableList;
    private javax.swing.JLabel LeaveTypeLabel;
    private javax.swing.JComboBox<String> LeaveTypeList;
    private javax.swing.JTextField LocalityField;
    private javax.swing.JLabel LocalityLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JTextField MobileField;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JTextField MotherField;
    private javax.swing.JLabel MotherNameLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField NewPass;
    private javax.swing.JLabel NewPasswordLabel;
    private javax.swing.JTextField OccupationField;
    private javax.swing.JLabel OccupationLabel;
    private javax.swing.JTextArea OffetTxt;
    private javax.swing.JPasswordField OldPass;
    private javax.swing.JLabel OldPasswordLabel;
    private javax.swing.JPanel PersonalDetailTab;
    private javax.swing.JLabel PinCodeLabel;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JTextArea ReasonTxt;
    private javax.swing.JScrollPane ReasonTxtPane;
    private javax.swing.JButton RejectBtn;
    private javax.swing.JButton ResignRequest;
    private javax.swing.JPanel Resignation;
    private javax.swing.JButton ResignationButton;
    private javax.swing.JTextArea SelfReview;
    private javax.swing.JLabel SelfReviewLabel;
    private javax.swing.JScrollPane SelfReviewPane;
    private javax.swing.JSeparator SeperatorLine;
    private javax.swing.JSeparator SeperatorLine2;
    private javax.swing.JPanel SideMenuPanel;
    private javax.swing.JButton SignOutEmpBtn;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel StatusLabelLeave;
    private javax.swing.JTextField StatusLeave;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JButton Submit;
    private javax.swing.JButton SubmitLeaveRequest;
    private javax.swing.JButton ViewLeave;
    private javax.swing.JPanel WelcomeDefaultLabelEmp;
    private javax.swing.JLabel WelcomeImg;
    private javax.swing.JScrollPane WorkDeliverdPane;
    private javax.swing.JTextArea WorkDelivered;
    private javax.swing.JLabel WorkDeliveredLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField graduationField;
    private javax.swing.JTextField graduationFieldCGPA;
    private javax.swing.JTextField highschoolField;
    private javax.swing.JTextField highschoolFieldCGPA;
    private javax.swing.JTextField interFieldCGPA;
    private javax.swing.JPanel myDataPanel;
    private javax.swing.JLabel offerLabel;
    private javax.swing.JTextField pincodeField;
    private javax.swing.JTextField rating;
    private javax.swing.JTextField stateField;
    private javax.swing.JLabel titleEmp;
    private javax.swing.JLabel titleEmp1;
    private javax.swing.JLabel titleEmp2;
    private javax.swing.JLabel titleEmp3;
    // End of variables declaration//GEN-END:variables
    private String encryptPassword(String TxtPass) throws NoSuchAlgorithmException {
        MessageDigest m = MessageDigest.getInstance("MD5");  
        m.update(TxtPass.getBytes());     
        byte[] bytes = m.digest();   
        StringBuilder s = new StringBuilder();  
        for(int i=0; i< bytes.length ;i++)  
        {  
            s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));  
        }  
        return(s.toString()); 
    }
    
    public void LeaveTableSetValue() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
        Statement stmt = conn.createStatement();
        PreparedStatement pstmt = conn.prepareStatement("SELECT ID,Date,Days,Status FROM applyleave where Username = ?");
        pstmt.setString(1, getUsername);
        ResultSet rs = pstmt.executeQuery();
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        DefaultTableModel tbmodel = (DefaultTableModel)LeaveTableList.getModel();
        tbmodel.getDataVector().removeAllElements();
        tbmodel.fireTableDataChanged();
        while (rs.next()) {
            Vector<Object> row = new Vector<Object>();
            for (int column = 1; column <= columnCount; column++) {
                row.add(rs.getObject(column));
            }
            tbmodel.addRow(row);
        }
        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }
    
    
    private void leaveDetailMethod(String leaveid){
        if(!leaveid.equalsIgnoreCase("NEW")){
            SubmitLeaveRequest.setVisible(false);
            LeaveStartDateTxt.setEditable(false);
            LeaveDaysTxt.setEditable(false);
            LeaveReasonTxt.setEditable(false);
            StatusLeave.setEditable(false);
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "")) {
             PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM applyleave where id = ?");
             pstmt.setString(1,leaveid);
             ResultSet rs = pstmt.executeQuery();
             if(rs.next()) {
                 LeaveStartDateTxt.setText(rs.getString("Date"));
                 LeaveDaysTxt.setText(rs.getString("Days"));
                 LeaveReasonTxt.setText(rs.getString("Reason"));
                 StatusLeave.setText(rs.getString("Status"));
             }
             else{
                 LeaveRequestButton.doClick();
                 JOptionPane.showMessageDialog(null, "Please Enter a Valid Leave ID");
                 
             }
             pstmt.close();
             conn.close();
             
            }  
            catch (SQLException ex) {
                Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    } 
}
