/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class HRHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HRHomeScreen
     */
    public HRHomeScreen() {
        initComponents();
        LeaveRequestPanel.setVisible(false);
        AppraisalPanel.setVisible(false);
        HireApplicantPanel.setVisible(false);
        ResignationPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        MainScreenTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HRLogin = new javax.swing.JButton();
        HRLogin1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SideMenuLabel = new javax.swing.JPanel();
        LogoAdmin = new javax.swing.JLabel();
        WelcomeBackLabel = new javax.swing.JLabel();
        SeperatorLine = new javax.swing.JSeparator();
        MenuLabel = new javax.swing.JLabel();
        SeperatorLine2 = new javax.swing.JSeparator();
        MenuPanel1 = new javax.swing.JPanel();
        HireIcon = new javax.swing.JLabel();
        HireNowButton = new javax.swing.JButton();
        MenuPanel2 = new javax.swing.JPanel();
        AppraisalIcon = new javax.swing.JLabel();
        AppraisalButton = new javax.swing.JButton();
        MenuPanel3 = new javax.swing.JPanel();
        ResignationIcon = new javax.swing.JLabel();
        ResignMenuBtn = new javax.swing.JButton();
        MenuPanel4 = new javax.swing.JPanel();
        LogoutIcon = new javax.swing.JLabel();
        LeaveBtn = new javax.swing.JButton();
        SignOutButton = new javax.swing.JButton();
        WelcomeDefaultLabel = new javax.swing.JPanel();
        WelcomeImage = new javax.swing.JLabel();
        HireApplicantPanel = new javax.swing.JPanel();
        HireApplicantLabel = new javax.swing.JLabel();
        EnterUserIDLabel = new javax.swing.JLabel();
        UserIDText = new javax.swing.JTextField();
        HiredButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        HireListTablePane = new javax.swing.JScrollPane();
        hireTabel = new javax.swing.JTable();
        AppraisalPanel = new javax.swing.JPanel();
        AppraisalTitleLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        RatingTxt = new javax.swing.JTextField();
        RateBtn = new javax.swing.JButton();
        CommentLabel = new javax.swing.JLabel();
        CommentPane = new javax.swing.JScrollPane();
        CommentTxtArea = new javax.swing.JTextArea();
        UserIDPerformanceTxt = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rateTable = new javax.swing.JTable();
        ResignationPanel = new javax.swing.JPanel();
        ResignationTitleLabel = new javax.swing.JLabel();
        OfferBtn = new javax.swing.JButton();
        AccepSepBtn1 = new javax.swing.JButton();
        CommentResignationLabel = new javax.swing.JLabel();
        ResignationTablePane = new javax.swing.JScrollPane();
        SepTable = new javax.swing.JTable();
        UserIDSeperationTxt = new javax.swing.JTextField();
        MakeOfferLabel = new javax.swing.JLabel();
        MakeOfferTxt = new javax.swing.JComboBox<>();
        UserIDLabelSepLabel = new javax.swing.JLabel();
        CommentResignationPane = new javax.swing.JScrollPane();
        CommentResignationTxtArea = new javax.swing.JTextArea();
        LeaveRequestPanel = new javax.swing.JPanel();
        LeaveReqTitleLabel = new javax.swing.JLabel();
        LeaveTablePane = new javax.swing.JScrollPane();
        LeaveTable = new javax.swing.JTable();
        LeaveIDLabel = new javax.swing.JLabel();
        LeaveIDTxt = new javax.swing.JTextField();
        RejectLeaveBtn = new javax.swing.JButton();
        ApproveLeaveBtn = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainScreenTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        MainScreenTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainScreenTitle.setText("HRDC-LOGIN");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HRLogin.setText("Employee");
        HRLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRLoginActionPerformed(evt);
            }
        });
        jPanel1.add(HRLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 151, 71));

        HRLogin1.setText("HR");
        HRLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(HRLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 151, 71));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(MainScreenTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(MainScreenTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1120, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideMenuLabel.setBackground(new java.awt.Color(102, 102, 255));
        SideMenuLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        LogoAdmin.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-administrator-male-100.png")); // NOI18N
        SideMenuLabel.add(LogoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, 90));

        WelcomeBackLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WelcomeBackLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeBackLabel.setText("Welcome Back !");
        SideMenuLabel.add(WelcomeBackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        SideMenuLabel.add(SeperatorLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 310, 10));

        MenuLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        MenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        MenuLabel.setText("Menu");
        SideMenuLabel.add(MenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 60, -1));
        SideMenuLabel.add(SeperatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 310, 10));

        HireIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-hire-me-50.png")); // NOI18N
        HireIcon.setText("jLabel9");

        HireNowButton.setBackground(new java.awt.Color(102, 102, 255));
        HireNowButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HireNowButton.setForeground(new java.awt.Color(255, 255, 255));
        HireNowButton.setText("Hire Now");
        HireNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HireNowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel1Layout = new javax.swing.GroupLayout(MenuPanel1);
        MenuPanel1.setLayout(MenuPanel1Layout);
        MenuPanel1Layout.setHorizontalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HireNowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(HireIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        MenuPanel1Layout.setVerticalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(HireIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HireNowButton)
                .addContainerGap())
        );

        SideMenuLabel.add(MenuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 130));

        AppraisalIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-appraisal-64.png")); // NOI18N
        AppraisalIcon.setText("jLabel10");

        AppraisalButton.setBackground(new java.awt.Color(102, 102, 255));
        AppraisalButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AppraisalButton.setForeground(new java.awt.Color(255, 255, 255));
        AppraisalButton.setText("Appraisal");
        AppraisalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppraisalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel2Layout = new javax.swing.GroupLayout(MenuPanel2);
        MenuPanel2.setLayout(MenuPanel2Layout);
        MenuPanel2Layout.setHorizontalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel2Layout.createSequentialGroup()
                .addGroup(MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AppraisalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AppraisalIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanel2Layout.setVerticalGroup(
            MenuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(AppraisalIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AppraisalButton)
                .addContainerGap())
        );

        SideMenuLabel.add(MenuPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 130));

        ResignationIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-retirement-48.png")); // NOI18N
        ResignationIcon.setText("jLabel11");

        ResignMenuBtn.setBackground(new java.awt.Color(102, 102, 255));
        ResignMenuBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResignMenuBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResignMenuBtn.setText("Resignation");
        ResignMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResignMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel3Layout = new javax.swing.GroupLayout(MenuPanel3);
        MenuPanel3.setLayout(MenuPanel3Layout);
        MenuPanel3Layout.setHorizontalGroup(
            MenuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResignMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ResignationIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanel3Layout.setVerticalGroup(
            MenuPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(ResignationIcon)
                .addGap(18, 18, 18)
                .addComponent(ResignMenuBtn)
                .addContainerGap())
        );

        SideMenuLabel.add(MenuPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 130));

        LogoutIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-data-transfer-64.png")); // NOI18N
        LogoutIcon.setText("jLabel12");

        LeaveBtn.setBackground(new java.awt.Color(102, 51, 255));
        LeaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        LeaveBtn.setText("Leave");
        LeaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel4Layout = new javax.swing.GroupLayout(MenuPanel4);
        MenuPanel4.setLayout(MenuPanel4Layout);
        MenuPanel4Layout.setHorizontalGroup(
            MenuPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LogoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(MenuPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuPanel4Layout.setVerticalGroup(
            MenuPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(LogoutIcon)
                .addGap(18, 18, 18)
                .addComponent(LeaveBtn)
                .addContainerGap())
        );

        SideMenuLabel.add(MenuPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, 130));

        SignOutButton.setBackground(new java.awt.Color(255, 51, 51));
        SignOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignOutButton.setForeground(new java.awt.Color(255, 255, 255));
        SignOutButton.setText("Sign out");
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });
        SideMenuLabel.add(SignOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 543, 270, 30));

        getContentPane().add(SideMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));

        WelcomeDefaultLabel.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeDefaultLabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeImage.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\welcome.jpg")); // NOI18N
        WelcomeDefaultLabel.add(WelcomeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        getContentPane().add(WelcomeDefaultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 800, 600));

        HireApplicantPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HireApplicantLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HireApplicantLabel.setText("Hire Applicant");
        HireApplicantPanel.add(HireApplicantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        EnterUserIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EnterUserIDLabel.setText("Enter User ID");
        HireApplicantPanel.add(EnterUserIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        UserIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDTextActionPerformed(evt);
            }
        });
        HireApplicantPanel.add(UserIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 250, 30));

        HiredButton.setBackground(new java.awt.Color(0, 204, 0));
        HiredButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HiredButton.setForeground(new java.awt.Color(255, 255, 255));
        HiredButton.setText("Hire");
        HiredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HiredButtonActionPerformed(evt);
            }
        });
        HireApplicantPanel.add(HiredButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 90, 30));

        RejectButton.setBackground(new java.awt.Color(255, 51, 0));
        RejectButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RejectButton.setForeground(new java.awt.Color(255, 255, 255));
        RejectButton.setText("Reject");
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });
        HireApplicantPanel.add(RejectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 460, 90, 30));

        hireTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Name", "isHired"
            }
        ));
        HireListTablePane.setViewportView(hireTabel);

        HireApplicantPanel.add(HireListTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 670, 260));

        getContentPane().add(HireApplicantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 750, 600));

        AppraisalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AppraisalTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AppraisalTitleLabel.setText("Appraisal");
        AppraisalPanel.add(AppraisalTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        RatingLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        RatingLabel.setText("Rating");
        AppraisalPanel.add(RatingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, -1, 20));

        RatingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingTxtActionPerformed(evt);
            }
        });
        AppraisalPanel.add(RatingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 80, 40));

        RateBtn.setBackground(new java.awt.Color(51, 51, 255));
        RateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RateBtn.setForeground(new java.awt.Color(255, 255, 255));
        RateBtn.setText("Rate");
        RateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateBtnActionPerformed(evt);
            }
        });
        AppraisalPanel.add(RateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 120, 40));

        CommentLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        CommentLabel.setText("Comment");
        AppraisalPanel.add(CommentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        CommentTxtArea.setColumns(20);
        CommentTxtArea.setRows(5);
        CommentPane.setViewportView(CommentTxtArea);

        AppraisalPanel.add(CommentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 560, 90));

        UserIDPerformanceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDPerformanceTxtActionPerformed(evt);
            }
        });
        AppraisalPanel.add(UserIDPerformanceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 180, 40));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        UsernameLabel.setText("Username");
        AppraisalPanel.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, 20));

        rateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "Work", "Learning", "Improvement", "Self Review"
            }
        ));
        jScrollPane1.setViewportView(rateTable);

        AppraisalPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 660, 220));

        getContentPane().add(AppraisalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 750, 600));

        ResignationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResignationTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ResignationTitleLabel.setText("Resignation");
        ResignationPanel.add(ResignationTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        OfferBtn.setBackground(new java.awt.Color(0, 204, 0));
        OfferBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OfferBtn.setForeground(new java.awt.Color(255, 255, 255));
        OfferBtn.setText("Offer");
        OfferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfferBtnActionPerformed(evt);
            }
        });
        ResignationPanel.add(OfferBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 120, 40));

        AccepSepBtn1.setBackground(new java.awt.Color(255, 51, 0));
        AccepSepBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AccepSepBtn1.setForeground(new java.awt.Color(255, 255, 255));
        AccepSepBtn1.setText("Accept");
        AccepSepBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccepSepBtn1ActionPerformed(evt);
            }
        });
        ResignationPanel.add(AccepSepBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 120, 40));

        CommentResignationLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        CommentResignationLabel.setText("Comment");
        ResignationPanel.add(CommentResignationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 30));

        SepTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Reason", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResignationTablePane.setViewportView(SepTable);
        if (SepTable.getColumnModel().getColumnCount() > 0) {
            SepTable.getColumnModel().getColumn(0).setResizable(false);
            SepTable.getColumnModel().getColumn(1).setResizable(false);
            SepTable.getColumnModel().getColumn(2).setResizable(false);
        }

        ResignationPanel.add(ResignationTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 600, 190));

        UserIDSeperationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDSeperationTxtActionPerformed(evt);
            }
        });
        ResignationPanel.add(UserIDSeperationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 270, 30));

        MakeOfferLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        MakeOfferLabel.setText("Make Offer");
        ResignationPanel.add(MakeOfferLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 90, 30));

        MakeOfferTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 LPA", "10 LPA", "15 LPA", "20 LPA", "25 LPA","30 LPA", "35 LPA", "40 LPA", "45 LPA", "50 LPA"  }));
        ResignationPanel.add(MakeOfferTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 180, 30));

        UserIDLabelSepLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        UserIDLabelSepLabel.setText("Username");
        ResignationPanel.add(UserIDLabelSepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 30));

        CommentResignationTxtArea.setColumns(20);
        CommentResignationTxtArea.setRows(5);
        CommentResignationPane.setViewportView(CommentResignationTxtArea);

        ResignationPanel.add(CommentResignationPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 250, -1));

        getContentPane().add(ResignationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 750, 600));

        LeaveRequestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeaveReqTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LeaveReqTitleLabel.setText("Leave Request Recieved");
        LeaveRequestPanel.add(LeaveReqTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        LeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Leave ID", "Username", "Date", "Days", "Reason"
            }
        ));
        LeaveTablePane.setViewportView(LeaveTable);

        LeaveRequestPanel.add(LeaveTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 680, 290));

        LeaveIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LeaveIDLabel.setText("LEAVE ID");
        LeaveRequestPanel.add(LeaveIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 80, 40));
        LeaveRequestPanel.add(LeaveIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 340, 40));

        RejectLeaveBtn.setBackground(new java.awt.Color(255, 0, 51));
        RejectLeaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        RejectLeaveBtn.setText("Reject");
        RejectLeaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectLeaveBtnActionPerformed(evt);
            }
        });
        LeaveRequestPanel.add(RejectLeaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 120, 40));

        ApproveLeaveBtn.setBackground(new java.awt.Color(0, 204, 0));
        ApproveLeaveBtn.setForeground(new java.awt.Color(255, 255, 255));
        ApproveLeaveBtn.setText("Approve");
        ApproveLeaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveLeaveBtnActionPerformed(evt);
            }
        });
        LeaveRequestPanel.add(ApproveLeaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 120, 40));

        getContentPane().add(LeaveRequestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HRLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRLoginActionPerformed
        dispose();
        HRHomeScreen hrHomescreen = new HRHomeScreen();
        hrHomescreen.setVisible(true);
    }//GEN-LAST:event_HRLoginActionPerformed

    private void HRLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRLogin1ActionPerformed

    }//GEN-LAST:event_HRLogin1ActionPerformed

    private void HireNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HireNowButtonActionPerformed
        // TODO add your handling code here:
        LeaveRequestPanel.setVisible(false);
        ResignationPanel.setVisible(false);
        AppraisalPanel.setVisible(false);
        HireApplicantPanel.setVisible(true);
        WelcomeDefaultLabel.setVisible(false);
        hireNow();
    }//GEN-LAST:event_HireNowButtonActionPerformed

    private void AppraisalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppraisalButtonActionPerformed
        // TODO add your handling code here:
        LeaveRequestPanel.setVisible(false);
        ResignationPanel.setVisible(false);
        AppraisalPanel.setVisible(true);
        HireApplicantPanel.setVisible(false);
        WelcomeDefaultLabel.setVisible(false);
        rateNow();
        
    }//GEN-LAST:event_AppraisalButtonActionPerformed

    private void UserIDPerformanceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDPerformanceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDPerformanceTxtActionPerformed

    private void RateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateBtnActionPerformed
        String user = UserIDPerformanceTxt.getText();
        String comment = CommentTxtArea.getText();
        int rating =  Integer.parseInt(RatingTxt.getText());
        DBConnection dbcon = new DBConnection();
        try {
            dbcon.reviewAppraisal(comment, rating,user);
            JOptionPane.showMessageDialog(null, "Appraisal Reviwed");
        } catch (SQLException ex) {
            Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RateBtnActionPerformed

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        dispose();
        MainScreen mn = new MainScreen();
        mn.setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    private void UserIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDTextActionPerformed

    private void HiredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HiredButtonActionPerformed
        try {
            String user = UserIDText.getText();
            DBConnection dbcon = new DBConnection();
            dbcon.applicationStatus("y",user);
            JOptionPane.showMessageDialog(null, "Application Accepted");
            HireNowButton.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HiredButtonActionPerformed

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        try {
            String user = UserIDText.getText();
            DBConnection dbcon = new DBConnection();
            dbcon.applicationStatus("r",user);
            JOptionPane.showMessageDialog(null, "Application Rejected");
            HireNowButton.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void ResignMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResignMenuBtnActionPerformed
        // TODO add your handling code here:
        LeaveRequestPanel.setVisible(false);
        ResignationPanel.setVisible(true);
        AppraisalPanel.setVisible(false);
        HireApplicantPanel.setVisible(false);
        WelcomeDefaultLabel.setVisible(false);
        ResignationList();
    }//GEN-LAST:event_ResignMenuBtnActionPerformed

    private void RatingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatingTxtActionPerformed

    private void OfferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfferBtnActionPerformed
        // TODO add your handling code here:                                     
        String user = UserIDSeperationTxt.getText();
        String offerTxt = String.valueOf(MakeOfferTxt.getSelectedItem());
        if(!user.equalsIgnoreCase("") && !offerTxt.equalsIgnoreCase("")){
            try {
                String cmnt = CommentResignationTxtArea.getText();
                DBConnection dbcon = new DBConnection();
                dbcon.makeOffer(user,offerTxt,cmnt);
                JOptionPane.showMessageDialog(null, "Employee Offered");
                ResignMenuBtn.doClick();
            } catch (SQLException ex) {
                Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter a valid Username");
        }
    }//GEN-LAST:event_OfferBtnActionPerformed

    private void AccepSepBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccepSepBtn1ActionPerformed
        // TODO add your handling code here:
        String user = UserIDSeperationTxt.getText();
        if(!user.equalsIgnoreCase("")){
            DBConnection dbconn = new DBConnection();
            try {
                dbconn.rejectHROffer(user);
                dbconn.acceptHROffer( user);
                JOptionPane.showMessageDialog(null, "Employee Resignation Request Accepted");
                ResignMenuBtn.doClick();;
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter a valid Username");
        }
    }//GEN-LAST:event_AccepSepBtn1ActionPerformed

    private void UserIDSeperationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDSeperationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDSeperationTxtActionPerformed

    private void LeaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveBtnActionPerformed
        // TODO add your handling code here:
        LeaveRequestPanel.setVisible(true);
        ResignationPanel.setVisible(false);
        AppraisalPanel.setVisible(false);
        HireApplicantPanel.setVisible(false);
        WelcomeDefaultLabel.setVisible(false);
        LeaveList();
    }//GEN-LAST:event_LeaveBtnActionPerformed

    private void ApproveLeaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveLeaveBtnActionPerformed
        // TODO add your handling code here:
        String id  = LeaveIDTxt.getText();
        DBConnection dbcon = new DBConnection();
        try {
            dbcon.acceptLeave(id);
            JOptionPane.showMessageDialog(null, "Leave #"+ id +" Accepted");
            LeaveBtn.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ApproveLeaveBtnActionPerformed

    private void RejectLeaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectLeaveBtnActionPerformed
        // TODO add your handling code here:
        String id  = LeaveIDTxt.getText();
        DBConnection dbcon = new DBConnection();
        try {
            dbcon.rejectLeave(id);
            JOptionPane.showMessageDialog(null, "Leave #"+ id +" Rejected");
            LeaveBtn.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(HRHomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RejectLeaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccepSepBtn1;
    private javax.swing.JButton AppraisalButton;
    private javax.swing.JLabel AppraisalIcon;
    private javax.swing.JPanel AppraisalPanel;
    private javax.swing.JLabel AppraisalTitleLabel;
    private javax.swing.JButton ApproveLeaveBtn;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JScrollPane CommentPane;
    private javax.swing.JLabel CommentResignationLabel;
    private javax.swing.JScrollPane CommentResignationPane;
    private javax.swing.JTextArea CommentResignationTxtArea;
    private javax.swing.JTextArea CommentTxtArea;
    private javax.swing.JLabel EnterUserIDLabel;
    private javax.swing.JButton HRLogin;
    private javax.swing.JButton HRLogin1;
    private javax.swing.JLabel HireApplicantLabel;
    private javax.swing.JPanel HireApplicantPanel;
    private javax.swing.JLabel HireIcon;
    private javax.swing.JScrollPane HireListTablePane;
    private javax.swing.JButton HireNowButton;
    private javax.swing.JButton HiredButton;
    private javax.swing.JButton LeaveBtn;
    private javax.swing.JLabel LeaveIDLabel;
    private javax.swing.JTextField LeaveIDTxt;
    private javax.swing.JLabel LeaveReqTitleLabel;
    private javax.swing.JPanel LeaveRequestPanel;
    private javax.swing.JTable LeaveTable;
    private javax.swing.JScrollPane LeaveTablePane;
    private javax.swing.JLabel LogoAdmin;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel MainScreenTitle;
    private javax.swing.JLabel MakeOfferLabel;
    private javax.swing.JComboBox<String> MakeOfferTxt;
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel MenuPanel1;
    private javax.swing.JPanel MenuPanel2;
    private javax.swing.JPanel MenuPanel3;
    private javax.swing.JPanel MenuPanel4;
    private javax.swing.JButton OfferBtn;
    private javax.swing.JButton RateBtn;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JTextField RatingTxt;
    private javax.swing.JButton RejectButton;
    private javax.swing.JButton RejectLeaveBtn;
    private javax.swing.JButton ResignMenuBtn;
    private javax.swing.JLabel ResignationIcon;
    private javax.swing.JPanel ResignationPanel;
    private javax.swing.JScrollPane ResignationTablePane;
    private javax.swing.JLabel ResignationTitleLabel;
    private javax.swing.JTable SepTable;
    private javax.swing.JSeparator SeperatorLine;
    private javax.swing.JSeparator SeperatorLine2;
    private javax.swing.JPanel SideMenuLabel;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel UserIDLabelSepLabel;
    private javax.swing.JTextField UserIDPerformanceTxt;
    private javax.swing.JTextField UserIDSeperationTxt;
    private javax.swing.JTextField UserIDText;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel WelcomeBackLabel;
    private javax.swing.JPanel WelcomeDefaultLabel;
    private javax.swing.JLabel WelcomeImage;
    private javax.swing.JTable hireTabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable rateTable;
    // End of variables declaration//GEN-END:variables

    
    
    public void hireNow() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "SELECT username,name,isHired FROM personaldetail where isHired = 'n'";
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            DefaultTableModel tbmodel = (DefaultTableModel)hireTabel.getModel();
            tbmodel.getDataVector().removeAllElements();
            tbmodel.fireTableDataChanged();
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>();
                for (int column = 1; column <= columnCount; column++) {
                    row.add(rs.getObject(column));
                }
                tbmodel.addRow(row);
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void rateNow() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "SELECT Username,Work,Learning,improvement,SelfReview FROM appraisal where reviewed = 'n'";
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            DefaultTableModel tbmodel = (DefaultTableModel)rateTable.getModel();
            tbmodel.getDataVector().removeAllElements();
            tbmodel.fireTableDataChanged();
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>();
                for (int column = 1; column <= columnCount; column++) {
                    row.add(rs.getObject(column));
                }
                tbmodel.addRow(row);
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void ResignationList() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
        Statement stmt = conn.createStatement();
        String sql = "SELECT Username,reason,status FROM resignation where status = 'PENDING'";
        ResultSet rs = stmt.executeQuery(sql);
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        DefaultTableModel tbmodel = (DefaultTableModel)SepTable.getModel();
        tbmodel.getDataVector().removeAllElements();
        tbmodel.fireTableDataChanged();
        while (rs.next()) {
            Vector<Object> row = new Vector<Object>();
            for (int column = 1; column <= columnCount; column++) {
                row.add(rs.getObject(column));
            }
            tbmodel.addRow(row);
        }
        rs.close();
        stmt.close();
        conn.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }
    public void LeaveList() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/HRDC", "root", "");
            Statement stmt = conn.createStatement();
            String sql = "SELECT ID,Username,Date,Days,Reason FROM applyleave where status = 'NEW'";
            ResultSet rs = stmt.executeQuery(sql);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            DefaultTableModel tbmodel = (DefaultTableModel)LeaveTable.getModel();
            tbmodel.getDataVector().removeAllElements();
            tbmodel.fireTableDataChanged();
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>();
                for (int column = 1; column <= columnCount; column++) {
                    row.add(rs.getObject(column));
                }
                tbmodel.addRow(row);
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
