/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.security.NoSuchAlgorithmException;  
import java.security.MessageDigest; 


public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        HRLogin.setVisible(false);
        JobApplyPannel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        MainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        EmpLogin = new javax.swing.JPanel();
        UsernameEmp = new javax.swing.JLabel();
        PassEmp = new javax.swing.JLabel();
        UsernameFieldEmp = new javax.swing.JTextField();
        PassFieldEmp = new javax.swing.JPasswordField();
        LoginEmpBtn = new javax.swing.JButton();
        TitleEmpLogin = new javax.swing.JLabel();
        HRLogin = new javax.swing.JPanel();
        UsernameHR = new javax.swing.JLabel();
        PassHR = new javax.swing.JLabel();
        UsernameFieldHR = new javax.swing.JTextField();
        PassFieldHR = new javax.swing.JPasswordField();
        LoginHRBtn = new javax.swing.JButton();
        TitleHRLogin = new javax.swing.JLabel();
        MainScreenTitleEmp = new javax.swing.JLabel();
        JobApplyPannel = new javax.swing.JPanel();
        RegScreenTitle = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        PersonalTab = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        MobileLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        dobField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        MobileField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        FaterNameLabel = new javax.swing.JLabel();
        MotherNameLabel = new javax.swing.JLabel();
        OccupationLabel = new javax.swing.JLabel();
        FatherField = new javax.swing.JTextField();
        MotherField = new javax.swing.JTextField();
        OccupationField = new javax.swing.JTextField();
        AddressTab = new javax.swing.JPanel();
        LocalityLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        CountryLabel = new javax.swing.JLabel();
        PinCodeLabel = new javax.swing.JLabel();
        LocalityField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        pincodeField = new javax.swing.JTextField();
        EducationTab = new javax.swing.JPanel();
        HighschoolLabel = new javax.swing.JLabel();
        HighschoolCGPALabel = new javax.swing.JLabel();
        HighSchoolCollegeLabel = new javax.swing.JLabel();
        highschoolFieldCGPA = new javax.swing.JTextField();
        highschoolField = new javax.swing.JTextField();
        InterLabel = new javax.swing.JLabel();
        InterCGPALabel = new javax.swing.JLabel();
        InterCollegeLabel = new javax.swing.JLabel();
        InterField = new javax.swing.JTextField();
        interFieldCGPA = new javax.swing.JTextField();
        GraduationLabel = new javax.swing.JLabel();
        GraduationCGPALabel = new javax.swing.JLabel();
        GraduationCollegeLabel = new javax.swing.JLabel();
        graduationField = new javax.swing.JTextField();
        graduationFieldCGPA = new javax.swing.JTextField();
        CreateIDTab = new javax.swing.JPanel();
        NewUserIDLabel = new javax.swing.JLabel();
        NewPassLabel = new javax.swing.JLabel();
        NewConfPassLabel = new javax.swing.JLabel();
        UserIDField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ConfPasswordField = new javax.swing.JPasswordField();
        SubmitTab = new javax.swing.JPanel();
        Accept = new javax.swing.JCheckBox();
        SignatureLabel = new javax.swing.JLabel();
        Sign = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        EmployeeMenuPanel = new javax.swing.JPanel();
        EmployeeIcon1 = new javax.swing.JLabel();
        EmpLoginBtn = new javax.swing.JButton();
        HRMenuPanel = new javax.swing.JPanel();
        HRIcon = new javax.swing.JLabel();
        HRLoginBtn = new javax.swing.JButton();
        JobApplyMenuPanel = new javax.swing.JPanel();
        RegistrationIcon = new javax.swing.JLabel();
        RegistrationBtn = new javax.swing.JButton();
        ExitMenuPanel = new javax.swing.JPanel();
        ExitIcon = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        LogoImage = new javax.swing.JLabel();
        OrganizationNameImage = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HRDC");
        setBackground(new java.awt.Color(204, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1120, 630));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(102, 102, 255));
        MainPanel.setVisible(true);
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LoginPanelComponentHidden(evt);
            }
        });
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpLogin.setBackground(new java.awt.Color(102, 102, 255));
        EmpLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UsernameEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameEmp.setForeground(new java.awt.Color(255, 255, 255));
        UsernameEmp.setText("Username");

        PassEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PassEmp.setForeground(new java.awt.Color(255, 255, 255));
        PassEmp.setText("Password");

        UsernameFieldEmp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UsernameFieldEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldEmpActionPerformed(evt);
            }
        });

        LoginEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginEmpBtn.setText("Sign in");
        LoginEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginEmpBtnActionPerformed(evt);
            }
        });

        TitleEmpLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TitleEmpLogin.setForeground(new java.awt.Color(255, 255, 255));
        TitleEmpLogin.setText("Employee Login");

        javax.swing.GroupLayout EmpLoginLayout = new javax.swing.GroupLayout(EmpLogin);
        EmpLogin.setLayout(EmpLoginLayout);
        EmpLoginLayout.setHorizontalGroup(
            EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpLoginLayout.createSequentialGroup()
                .addGroup(EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpLoginLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(EmpLoginLayout.createSequentialGroup()
                                .addComponent(UsernameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EmpLoginLayout.createSequentialGroup()
                                .addComponent(PassEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PassFieldEmp))))
                    .addGroup(EmpLoginLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(TitleEmpLogin)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        EmpLoginLayout.setVerticalGroup(
            EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpLoginLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TitleEmpLogin)
                .addGap(43, 43, 43)
                .addGroup(EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpLoginLayout.createSequentialGroup()
                        .addComponent(UsernameEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EmpLoginLayout.createSequentialGroup()
                        .addComponent(UsernameFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(EmpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PassEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassFieldEmp))
                        .addGap(35, 35, 35)))
                .addComponent(LoginEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        LoginPanel.add(EmpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        HRLogin.setBackground(new java.awt.Color(102, 102, 255));
        HRLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        UsernameHR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameHR.setForeground(new java.awt.Color(255, 255, 255));
        UsernameHR.setText("Username");

        PassHR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PassHR.setForeground(new java.awt.Color(255, 255, 255));
        PassHR.setText("Password");

        UsernameFieldHR.setText("admin");
        UsernameFieldHR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UsernameFieldHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldHRActionPerformed(evt);
            }
        });

        LoginHRBtn.setText("Log in");
        LoginHRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginHRBtnActionPerformed(evt);
            }
        });

        TitleHRLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TitleHRLogin.setForeground(new java.awt.Color(255, 255, 255));
        TitleHRLogin.setText("HR Login");

        javax.swing.GroupLayout HRLoginLayout = new javax.swing.GroupLayout(HRLogin);
        HRLogin.setLayout(HRLoginLayout);
        HRLoginLayout.setHorizontalGroup(
            HRLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRLoginLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(HRLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginHRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HRLoginLayout.createSequentialGroup()
                        .addComponent(UsernameHR, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsernameFieldHR, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HRLoginLayout.createSequentialGroup()
                        .addComponent(PassHR, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassFieldHR)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HRLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleHRLogin)
                .addGap(221, 221, 221))
        );
        HRLoginLayout.setVerticalGroup(
            HRLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRLoginLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TitleHRLogin)
                .addGap(43, 43, 43)
                .addGroup(HRLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HRLoginLayout.createSequentialGroup()
                        .addComponent(UsernameHR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HRLoginLayout.createSequentialGroup()
                        .addComponent(UsernameFieldHR, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(HRLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PassHR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassFieldHR))
                        .addGap(35, 35, 35)))
                .addComponent(LoginHRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        LoginPanel.add(HRLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        MainScreenTitleEmp.setBackground(new java.awt.Color(255, 255, 255));
        MainScreenTitleEmp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MainScreenTitleEmp.setForeground(new java.awt.Color(102, 0, 102));
        MainScreenTitleEmp.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\HRDC.png")); // NOI18N
        LoginPanel.add(MainScreenTitleEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 160, 85));

        MainPanel.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 840, 510));

        JobApplyPannel.setBackground(new java.awt.Color(255, 255, 255));
        JobApplyPannel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                JobApplyPannelComponentHidden(evt);
            }
        });
        JobApplyPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegScreenTitle.setBackground(new java.awt.Color(255, 255, 255));
        RegScreenTitle.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        RegScreenTitle.setForeground(new java.awt.Color(102, 0, 102));
        RegScreenTitle.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\JOBAPPLICATION.png")); // NOI18N
        JobApplyPannel.add(RegScreenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 380, 60));

        TabbedPane.setBackground(new java.awt.Color(51, 51, 255));
        TabbedPane.setForeground(new java.awt.Color(255, 255, 255));

        PersonalTab.setBackground(new java.awt.Color(102, 102, 255));

        NameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name");

        DOBLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DOBLabel.setForeground(new java.awt.Color(255, 255, 255));
        DOBLabel.setText("Date of Birth");

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgeLabel.setText("Age");

        MobileLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MobileLabel.setForeground(new java.awt.Color(255, 255, 255));
        MobileLabel.setText("Mobile");

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        FaterNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FaterNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FaterNameLabel.setText("Father's Name");

        MotherNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MotherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        MotherNameLabel.setText("Mother's Name");

        OccupationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OccupationLabel.setForeground(new java.awt.Color(255, 255, 255));
        OccupationLabel.setText("Father's Occupation");

        javax.swing.GroupLayout PersonalTabLayout = new javax.swing.GroupLayout(PersonalTab);
        PersonalTab.setLayout(PersonalTabLayout);
        PersonalTabLayout.setHorizontalGroup(
            PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalTabLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MobileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MotherNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FaterNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OccupationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OccupationField)
                    .addComponent(AgeField)
                    .addComponent(emailField)
                    .addComponent(MobileField)
                    .addComponent(FatherField)
                    .addGroup(PersonalTabLayout.createSequentialGroup()
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MotherField)
                    .addComponent(dobField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(117, 117, 117))
        );
        PersonalTabLayout.setVerticalGroup(
            PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonalTabLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBLabel)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileLabel)
                    .addComponent(MobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FaterNameLabel)
                    .addComponent(FatherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MotherNameLabel)
                    .addComponent(MotherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PersonalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OccupationLabel)
                    .addComponent(OccupationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        TabbedPane.addTab("Personal Detail", PersonalTab);

        AddressTab.setBackground(new java.awt.Color(102, 102, 255));

        LocalityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LocalityLabel.setForeground(new java.awt.Color(255, 255, 255));
        LocalityLabel.setText("Locality");

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(255, 255, 255));
        CityLabel.setText("City");

        StateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateLabel.setText("State");

        CountryLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CountryLabel.setForeground(new java.awt.Color(255, 255, 255));
        CountryLabel.setText("Country");

        PinCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PinCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        PinCodeLabel.setText("Pin Code");

        javax.swing.GroupLayout AddressTabLayout = new javax.swing.GroupLayout(AddressTab);
        AddressTab.setLayout(AddressTabLayout);
        AddressTabLayout.setHorizontalGroup(
            AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressTabLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddressTabLayout.createSequentialGroup()
                        .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(AddressTabLayout.createSequentialGroup()
                        .addComponent(CountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LocalityField)
                    .addComponent(cityField)
                    .addComponent(stateField)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(PinCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        AddressTabLayout.setVerticalGroup(
            AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressTabLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalityLabel)
                    .addComponent(PinCodeLabel)
                    .addComponent(LocalityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateLabel)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(AddressTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryLabel)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        TabbedPane.addTab("Address Detail", AddressTab);

        EducationTab.setBackground(new java.awt.Color(102, 102, 255));

        HighschoolLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighschoolLabel.setForeground(new java.awt.Color(255, 255, 255));
        HighschoolLabel.setText("Highschool");

        HighschoolCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighschoolCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        HighschoolCGPALabel.setText("Percentage/CGPA");

        HighSchoolCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HighSchoolCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HighSchoolCollegeLabel.setText("School/College");

        InterLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterLabel.setForeground(new java.awt.Color(255, 255, 255));
        InterLabel.setText("Intemediate");

        InterCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        InterCGPALabel.setText("Percentage/CGPA");

        InterCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InterCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        InterCollegeLabel.setText("School/College");

        GraduationLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationLabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationLabel.setText("Graduation");

        GraduationCGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationCGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationCGPALabel.setText("Percentage/CGPA");

        GraduationCollegeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GraduationCollegeLabel.setForeground(new java.awt.Color(255, 255, 255));
        GraduationCollegeLabel.setText("School/College");

        javax.swing.GroupLayout EducationTabLayout = new javax.swing.GroupLayout(EducationTab);
        EducationTab.setLayout(EducationTabLayout);
        EducationTabLayout.setHorizontalGroup(
            EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HighschoolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GraduationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EducationTabLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GraduationCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GraduationCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(graduationField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                            .addComponent(graduationFieldCGPA))))
                                .addGroup(EducationTabLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(InterCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InterCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(InterField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                        .addComponent(interFieldCGPA)))))
                        .addGroup(EducationTabLayout.createSequentialGroup()
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HighSchoolCollegeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HighschoolCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(highschoolField, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                .addComponent(highschoolFieldCGPA)))))
                .addGap(0, 0, 0))
        );
        EducationTabLayout.setVerticalGroup(
            EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EducationTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(HighschoolLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highschoolFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HighschoolCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(highschoolField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HighSchoolCollegeLabel)))
                .addGap(30, 30, 30)
                .addComponent(InterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InterCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(InterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InterCollegeLabel)))
                .addGap(30, 30, 30)
                .addComponent(GraduationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graduationFieldCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GraduationCGPALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EducationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(graduationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EducationTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GraduationCollegeLabel)))
                .addGap(0, 0, 0))
        );

        TabbedPane.addTab("Education Detail", EducationTab);

        CreateIDTab.setBackground(new java.awt.Color(102, 102, 255));

        NewUserIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewUserIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        NewUserIDLabel.setText("UserID");
        NewUserIDLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewUserIDLabelFocusGained(evt);
            }
        });

        NewPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        NewPassLabel.setText("Password");

        NewConfPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewConfPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        NewConfPassLabel.setText("Confirm Password");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateIDTabLayout = new javax.swing.GroupLayout(CreateIDTab);
        CreateIDTab.setLayout(CreateIDTabLayout);
        CreateIDTabLayout.setHorizontalGroup(
            CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateIDTabLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewConfPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserIDField)
                    .addComponent(PasswordField)
                    .addComponent(ConfPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        CreateIDTabLayout.setVerticalGroup(
            CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateIDTabLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewUserIDLabel)
                    .addComponent(UserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPassLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(CreateIDTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewConfPassLabel)
                    .addComponent(ConfPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Create ID", CreateIDTab);

        SubmitTab.setBackground(new java.awt.Color(102, 102, 255));

        Accept.setBackground(new java.awt.Color(102, 102, 255));
        Accept.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Accept.setForeground(new java.awt.Color(255, 255, 255));
        Accept.setText("Accept Terms & Condition");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        SignatureLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignatureLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignatureLabel.setText("Signature");

        Submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubmitTabLayout = new javax.swing.GroupLayout(SubmitTab);
        SubmitTab.setLayout(SubmitTabLayout);
        SubmitTabLayout.setHorizontalGroup(
            SubmitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubmitTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sign, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(SubmitTabLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(SubmitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubmitTabLayout.createSequentialGroup()
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        SubmitTabLayout.setVerticalGroup(
            SubmitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubmitTabLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(SubmitTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignatureLabel)
                    .addComponent(Sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Accept)
                .addGap(18, 18, 18)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Submit", SubmitTab);

        JobApplyPannel.add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 660, 370));

        MainPanel.add(JobApplyPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 840, 510));

        EmployeeMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        EmployeeMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EmployeeIcon1.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-person-48.png")); // NOI18N

        EmpLoginBtn.setBackground(new java.awt.Color(102, 102, 255));
        EmpLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmpLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmpLoginBtn.setText("Employee");
        EmpLoginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EmpLoginBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        EmpLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeMenuPanelLayout = new javax.swing.GroupLayout(EmployeeMenuPanel);
        EmployeeMenuPanel.setLayout(EmployeeMenuPanelLayout);
        EmployeeMenuPanelLayout.setHorizontalGroup(
            EmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(EmployeeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmpLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        EmployeeMenuPanelLayout.setVerticalGroup(
            EmployeeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeMenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(EmployeeIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        MainPanel.add(EmployeeMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 120));

        HRMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        HRMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        HRIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-administrator-male-48.png")); // NOI18N
        HRIcon.setText("jLabel2");

        HRLoginBtn.setBackground(new java.awt.Color(102, 102, 255));
        HRLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HRLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        HRLoginBtn.setText("HR");
        HRLoginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HRLoginBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        HRLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HRMenuPanelLayout = new javax.swing.GroupLayout(HRMenuPanel);
        HRMenuPanel.setLayout(HRMenuPanelLayout);
        HRMenuPanelLayout.setHorizontalGroup(
            HRMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRMenuPanelLayout.createSequentialGroup()
                .addGroup(HRMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HRMenuPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(HRIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HRMenuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(HRLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        HRMenuPanelLayout.setVerticalGroup(
            HRMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRMenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(HRIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HRLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(HRMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        JobApplyMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        JobApplyMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        RegistrationIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-registration-48.png")); // NOI18N
        RegistrationIcon.setText("jLabel3");

        RegistrationBtn.setBackground(new java.awt.Color(102, 102, 255));
        RegistrationBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistrationBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationBtn.setText("Job Apply");
        RegistrationBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegistrationBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        RegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JobApplyMenuPanelLayout = new javax.swing.GroupLayout(JobApplyMenuPanel);
        JobApplyMenuPanel.setLayout(JobApplyMenuPanelLayout);
        JobApplyMenuPanelLayout.setHorizontalGroup(
            JobApplyMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobApplyMenuPanelLayout.createSequentialGroup()
                .addGroup(JobApplyMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JobApplyMenuPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(RegistrationIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JobApplyMenuPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(RegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JobApplyMenuPanelLayout.setVerticalGroup(
            JobApplyMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobApplyMenuPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RegistrationIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(JobApplyMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        ExitMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitMenuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ExitIcon.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\icons8-shutdown-48.png")); // NOI18N

        ExitBtn.setBackground(new java.awt.Color(255, 51, 51));
        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("Exit");
        ExitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExitBtn.setPreferredSize(new java.awt.Dimension(60, 30));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitMenuPanelLayout = new javax.swing.GroupLayout(ExitMenuPanel);
        ExitMenuPanel.setLayout(ExitMenuPanelLayout);
        ExitMenuPanelLayout.setHorizontalGroup(
            ExitMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitMenuPanelLayout.createSequentialGroup()
                .addGroup(ExitMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExitMenuPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ExitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExitMenuPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ExitMenuPanelLayout.setVerticalGroup(
            ExitMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitMenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ExitIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(ExitMenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        LogoImage.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\HRDC-SYSTEM (2).jpg")); // NOI18N
        MainPanel.add(LogoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 150));

        OrganizationNameImage.setIcon(new javax.swing.ImageIcon("E:\\HRDC\\mavenproject1\\src\\Image\\HUMANRESOURCE.png")); // NOI18N
        MainPanel.add(OrganizationNameImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LoginPanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPanelComponentHidden
    
    private void LoginEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginEmpBtnActionPerformed
        String TxtUsername = UsernameFieldEmp.getText();
	String TxtPass = new String(PassFieldEmp.getPassword());
        String TxtPassword = null;
        try {
            TxtPassword = encryptPassword(TxtPass);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        String accStatus="n";
        DBConnection dbcon = new DBConnection();
        try {
            accStatus= dbcon.getName("isHired",TxtUsername);
            if(accStatus.equals("")) {
		JOptionPane.showMessageDialog(null, "User not Found!");
            }
            else if(accStatus.equals("n")){
                JOptionPane.showMessageDialog(null, "User not Active! Please contact Administrator");
            }
            else if(accStatus.equals("r")){
                JOptionPane.showMessageDialog(null, "Sorry! :( Youy Application has been Rejected.....");
            }
            else if(accStatus.equals("y")) {
                String dbPassword = dbcon.getName("password",TxtUsername);
            if(dbPassword.equals(TxtPassword)) {
                dispose(); 
          
                EmployeeHomeScreen employeeHomeScreen = new EmployeeHomeScreen(TxtUsername);
                employeeHomeScreen.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Password did not match!");
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoginEmpBtnActionPerformed

    private void UsernameFieldEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldEmpActionPerformed

    private void EmpLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpLoginBtnActionPerformed
        JobApplyPannel.setVisible(false);
        LoginPanel.setVisible(true);
        EmpLogin.setVisible(true);   
        HRLogin.setVisible(false);
        JobApplyPannel.setVisible(false);
        
    }//GEN-LAST:event_EmpLoginBtnActionPerformed
    
    
    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void HRLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRLoginBtnActionPerformed
        JobApplyPannel.setVisible(false);
        LoginPanel.setVisible(true);
        EmpLogin.setVisible(false);   
        JobApplyPannel.setVisible(false);
        HRLogin.setVisible(true);
        
    }//GEN-LAST:event_HRLoginBtnActionPerformed

    private void UsernameFieldHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldHRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldHRActionPerformed

    private void LoginHRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginHRBtnActionPerformed
        String TxtUsername = UsernameFieldHR.getText();
	String TxtPassword = new String(PassFieldHR.getPassword());
        if(TxtUsername.equals("admin") && TxtPassword.equals("admin@123")){
            dispose(); 
            HRHomeScreen hrHomeScreen = new HRHomeScreen();
            hrHomeScreen.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Password did not match!");
        }
    }//GEN-LAST:event_LoginHRBtnActionPerformed

    private void JobApplyPannelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JobApplyPannelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_JobApplyPannelComponentHidden

    private void RegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationBtnActionPerformed
        LoginPanel.setVisible(false);   
        JobApplyPannel.setVisible(true);
    }//GEN-LAST:event_RegistrationBtnActionPerformed

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String TxtUsername = UserIDField.getText();
        String TxtPass = new String(PasswordField.getPassword());
        String TxtPassword = null;
        if(TxtPass.length() >= 8){
            try {
                TxtPassword = encryptPassword(TxtPass);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            String TxtConfPassword = new String(ConfPasswordField.getPassword());
            String TxtName = NameField.getText();
            int TxtAge = Integer.parseInt(AgeField.getText());
            String TxtDateString = dobField.getText();
            String TxtMobile = MobileField.getText();
            String TxtEmail = emailField.getText();
            String TxtFather = FatherField.getText();
            String TxtMother = MotherField.getText();
            String TxtOccupation = OccupationField.getText();
            String TxtLocality = LocalityField.getText();
            String TxtCity = cityField.getText();
            String TxtState = stateField.getText();
            String TxtCountry = countryField.getText();
            int  TxtPincode = Integer.parseInt(pincodeField.getText());
            String TxtHS =  highschoolField.getText();
            String TxtInter = InterField.getText();
            String TxtGrad = graduationField.getText();
            int TxtCGPAHS = Integer.parseInt(highschoolFieldCGPA.getText());
            int TxtCGPAInter = Integer.parseInt(interFieldCGPA.getText());
            int TxtCGPAGrad = Integer.parseInt(graduationFieldCGPA.getText());
            String SignTxt = Sign.getText();

            if(Accept.isSelected() && !(SignTxt.equalsIgnoreCase(""))){
                if(TxtUsername.equalsIgnoreCase("") || TxtPassword.equalsIgnoreCase("") || TxtConfPassword.equalsIgnoreCase("") ){
                    JOptionPane.showMessageDialog(null, "UserID and Password Field can not be Empty");
                }
                else if(!(TxtPass.equals(TxtConfPassword))){
                    JOptionPane.showMessageDialog(null, "Password and Confirm Password must be same");
                }
                else{
                    DBConnection dbcon = new DBConnection();
                    try {
                        if(!(dbcon.getName(TxtPassword, TxtUsername)).equalsIgnoreCase("")){
                            JOptionPane.showMessageDialog(null, "UserID should be Unique");
                        }
                        else{
                            dbcon.insertData(TxtUsername,TxtPassword,TxtName,TxtAge,TxtDateString,TxtMobile,TxtEmail,TxtFather,TxtMother,TxtOccupation,TxtLocality,TxtCity,TxtState,TxtCountry,TxtPincode,TxtHS,TxtInter,TxtGrad,TxtCGPAHS,TxtCGPAInter,TxtCGPAGrad);
                            JOptionPane.showMessageDialog(null, "Registration Successful");

                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else{
                 JOptionPane.showMessageDialog(null, "Please Attach the Application and Accept Terms and Conditionsbefore Submitting");
            }
        }
        else{
           JOptionPane.showMessageDialog(null, "Password must be at least 8 Characters");
             
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void NewUserIDLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewUserIDLabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUserIDLabelFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Accept;
    private javax.swing.JPanel AddressTab;
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPasswordField ConfPasswordField;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JPanel CreateIDTab;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JPanel EducationTab;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel EmpLogin;
    private javax.swing.JButton EmpLoginBtn;
    private javax.swing.JLabel EmployeeIcon1;
    private javax.swing.JPanel EmployeeMenuPanel;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel ExitIcon;
    private javax.swing.JPanel ExitMenuPanel;
    private javax.swing.JLabel FaterNameLabel;
    private javax.swing.JTextField FatherField;
    private javax.swing.JLabel GraduationCGPALabel;
    private javax.swing.JLabel GraduationCollegeLabel;
    private javax.swing.JLabel GraduationLabel;
    private javax.swing.JLabel HRIcon;
    private javax.swing.JPanel HRLogin;
    private javax.swing.JButton HRLoginBtn;
    private javax.swing.JPanel HRMenuPanel;
    private javax.swing.JLabel HighSchoolCollegeLabel;
    private javax.swing.JLabel HighschoolCGPALabel;
    private javax.swing.JLabel HighschoolLabel;
    private javax.swing.JLabel InterCGPALabel;
    private javax.swing.JLabel InterCollegeLabel;
    private javax.swing.JTextField InterField;
    private javax.swing.JLabel InterLabel;
    private javax.swing.JPanel JobApplyMenuPanel;
    private javax.swing.JPanel JobApplyPannel;
    private javax.swing.JTextField LocalityField;
    private javax.swing.JLabel LocalityLabel;
    private javax.swing.JButton LoginEmpBtn;
    private javax.swing.JButton LoginHRBtn;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LogoImage;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MainScreenTitleEmp;
    private javax.swing.JTextField MobileField;
    private javax.swing.JLabel MobileLabel;
    private javax.swing.JTextField MotherField;
    private javax.swing.JLabel MotherNameLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NewConfPassLabel;
    private javax.swing.JLabel NewPassLabel;
    private javax.swing.JLabel NewUserIDLabel;
    private javax.swing.JTextField OccupationField;
    private javax.swing.JLabel OccupationLabel;
    private javax.swing.JLabel OrganizationNameImage;
    private javax.swing.JLabel PassEmp;
    private javax.swing.JPasswordField PassFieldEmp;
    private javax.swing.JPasswordField PassFieldHR;
    private javax.swing.JLabel PassHR;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel PersonalTab;
    private javax.swing.JLabel PinCodeLabel;
    private javax.swing.JLabel RegScreenTitle;
    private javax.swing.JButton RegistrationBtn;
    private javax.swing.JLabel RegistrationIcon;
    private javax.swing.JTextField Sign;
    private javax.swing.JLabel SignatureLabel;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JButton Submit;
    private javax.swing.JPanel SubmitTab;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel TitleEmpLogin;
    private javax.swing.JLabel TitleHRLogin;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel UsernameEmp;
    private javax.swing.JTextField UsernameFieldEmp;
    private javax.swing.JTextField UsernameFieldHR;
    private javax.swing.JLabel UsernameHR;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField dobField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField graduationField;
    private javax.swing.JTextField graduationFieldCGPA;
    private javax.swing.JTextField highschoolField;
    private javax.swing.JTextField highschoolFieldCGPA;
    private javax.swing.JTextField interFieldCGPA;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField pincodeField;
    private javax.swing.JTextField stateField;
    // End of variables declaration//GEN-END:variables

    private String encryptPassword(String TxtPass) throws NoSuchAlgorithmException {
        MessageDigest m = MessageDigest.getInstance("MD5");  
        m.update(TxtPass.getBytes());     
        byte[] bytes = m.digest();   
        StringBuilder s = new StringBuilder();  
        for(int i=0; i< bytes.length ;i++)  
        {  
            s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));  
        }  
        return(s.toString()); 
    }





}
